In [14]:
import pandas as pd
import folium
from pandas.io import sql 
import MySQLdb

con = MySQLdb.connect(user='root', password='',host='localhost', database='myfloodlaravel')
concursor = con.cursor()

df = pd.read_csv("latlongnewcombined.csv", names=['statid','lat','long']) 
df.dropna(inplace=True)
df

     statid       lat        long
0   3516424  3.541417  101.662333
1   3416403  3.469917  101.639806
2   3808401  3.856556  100.895833
3   3414421  3.402778  101.443056
4   3313445  3.371917  101.370500
5   3312446  3.342528  101.269111
6   3214401  3.246139  101.469694
7   3313470  3.306722  101.386444
8   3315401  3.304694  101.591944
9   3017445  3.014500  101.718667
10  3015436  3.019528  101.597417
11  3115403  3.112278  101.596444
12  3115404  3.150056  101.540944
13  3015490  3.096944  101.554167
14  3015435  3.075611  101.553889
15  3015432  3.037722  101.534500
16  3014401  3.048056  101.444806
17  3218401  3.209639  101.875861
18  2917401  2.994444  101.786111
19  3018401  3.013444  101.866056
20  2918401  2.915278  101.823611
21  2717401  2.788667  101.741972
22  2816441  2.992778  101.786944
23  2816443  2.813472  101.641917
24  3217435  3.236111  101.752778
25  3217403  3.245278  101.715278
26  3116434  3.176389  101.687500
27  3116433  3.173611  101.697222
28  3117403  3.169722  101.713333
29  3116439  3.151333  101.695306
30  3116436  3.112583  101.696583
31  3116430  3.138889  101.697222
32  3016401  3.080917  101.665194

In [15]:
df['value'] = ''
df['alert'] = ''
df['warning'] = ''
df['danger'] = ''
df['stationname'] = ''
df['lastupdate'] = ''
print(df)

     statid       lat        long value alert warning danger stationname  \
0   3516424  3.541417  101.662333
1   3416403  3.469917  101.639806
2   3808401  3.856556  100.895833
3   3414421  3.402778  101.443056
4   3313445  3.371917  101.370500
5   3312446  3.342528  101.269111
6   3214401  3.246139  101.469694
7   3313470  3.306722  101.386444
8   3315401  3.304694  101.591944
9   3017445  3.014500  101.718667
10  3015436  3.019528  101.597417
11  3115403  3.112278  101.596444
12  3115404  3.150056  101.540944
13  3015490  3.096944  101.554167
14  3015435  3.075611  101.553889
15  3015432  3.037722  101.534500
16  3014401  3.048056  101.444806
17  3218401  3.209639  101.875861
18  2917401  2.994444  101.786111
19  3018401  3.013444  101.866056
20  2918401  2.915278  101.823611
21  2717401  2.788667  101.741972
22  2816441  2.992778  101.786944
23  2816443  2.813472  101.641917
24  3217435  3.236111  101.752778
25  3217403  3.245278  101.715278
26  3116434  3.176389  101.687500
27  3116433  3.173611  101.697222
28  3117403  3.169722  101.713333
29  3116439  3.151333  101.695306
30  3116436  3.112583  101.696583
31  3116430  3.138889  101.697222
32  3016401  3.080917  101.665194

   lastupdate
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32

In [16]:
# con = MySQLdb.connect(user='root', password='',host='localhost', database='website_myflood')
# concursor = con.cursor()
#for selangor
for i in range(0,24):
   x = df['statid'][i]
   state = ("SELECT CurrentWaterLevel FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['value'][i] = result
for i in range(0,24):
   x = df['statid'][i]
   state = ("SELECT Alert FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['alert'][i] = result
for i in range(0,24):
   x = df['statid'][i]
   state = ("SELECT Warning FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['warning'][i] = result
for i in range(0,24):
   x = df['statid'][i]
   state = ("SELECT Danger FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['danger'][i] = result
for i in range(0,24):
   x = df['statid'][i]
   #state = ("SELECT `Station Name` FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute("SELECT `Station Name` FROM `selangorscrape` WHERE `Station ID` = '{x}'".format(x=x))
#concursor.execute("SELECT phonenum FROM users WHERE district = '{x}'".format(x=x))
   result = concursor.fetchall()
   print(result)
   df['stationname'][i] = result

for i in range(0,24):
   x = df['statid'][i]
   state = ("SELECT `Last Update` FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['lastupdate'][i] = result
    
#for kl 
for i in range(24,33):
   x = df['statid'][i]
   state = ("SELECT CurrentWaterLevel FROM `klscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['value'][i] = result
for i in range(24,33):
   x = df['statid'][i]
   state = ("SELECT Alert FROM `klscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['alert'][i] = result
for i in range(24,33):
   x = df['statid'][i]
   state = ("SELECT Warning FROM `klscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['warning'][i] = result
for i in range(24,33):
   x = df['statid'][i]
   state = ("SELECT Danger FROM `klscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['danger'][i] = result
for i in range(24,33):
   x = df['statid'][i]
   state = ("SELECT `Station Name` FROM `klscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['stationname'][i] = result
for i in range(24,33):
   x = df['statid'][i]
   state = ("SELECT `Last Update` FROM `klscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['lastupdate'][i] = result

KeyboardInterrupt:

In [ ]:
df

,statid,lat,long,value,alert,warning,danger,stationname,lastupdate
0,3516424,3.541417,101.662333,"((50.18,),)","((51.3,),)","((51.6,),)","((51.9,),)","((Sg. Selangor di Ampang Pecah,),)","((07/01/2023 12:30,),)"
1,3416403,3.469917,101.639806,"((32.66,),)","((35.2,),)","((35.5,),)","((35.8,),)","((Sg. Batang Kali di Batang Kali,),)","((07/01/2023 12:30,),)"
2,3808401,3.856556,100.895833,"((0.42,),)","((4.3,),)","((4.6,),)","((4.9,),)","((Sg. Bernam di Sg. Air Tawar,),)","((07/01/2023 12:30,),)"
3,3414421,3.402778,101.443056,"((6.35,),)","((6.8,),)","((7.3,),)","((7.8,),)","((Sg. Selangor di Rantau Panjang,),)","((07/01/2023 12:30,),)"
4,3313445,3.371917,101.370500,"((1.59,),)","((3.22,),)","((3.38,),)","((3.54,),)","((Sg. Selangor di Kg. Asahan,),)","((07/01/2023 12:30,),)"
5,3312446,3.342528,101.269111,"((-1.37,),)","((2.1,),)","((2.6,),)","((3.1,),)","((Sg. Selangor di Teluk Penyamun (Jeti),),)","((07/01/2023 12:15,),)"
6,3214401,3.246139,101.469694,"((4.23,),)","((6.5,),)","((7.0,),)","((7.5,),)","((Sg. Buloh di Sri Aman,),)","((07/01/2023 12:30,),)"
7,3313470,3.306722,101.386444,"((2.16,),)","((3.5,),)","((4.0,),)","((4.5,),)","((Sg. Buloh di Parit Mahang,),)","((07/01/2023 12:30,),)"
8,3315401,3.304694,101.591944,"((33.05,),)","((34.3,),)","((34.8,),)","((35.3,),)","((Sg. Rawang di Taman Tun Teja,),)","((07/01/2023 12:30,),)"
9,3017445,3.014500,101.718667,"((36.39,),)","((38.5,),)","((39.0,),)","((40.0,),)","((Sg. Kuyoh di Seri Kembangan,),)","((07/01/2023 12:30,),)"
10,3015436,3.019528,101.597417,"((5.36,),)","((9.0,),)","((9.5,),)","((10.0,),)","((Sg. Klang di Puchong Drop,),)","((07/01/2023 12:30,),)"
11,3115403,3.112278,101.596444,"((14.8,),)","((17.0,),)","((17.5,),)","((18.0,),)","((Sg. Kayu Ara di Taman Mayang,),)","((07/01/2023 12:30,),)"
12,3115404,3.150056,101.540944,"((15.14,),)","((16.4,),)","((16.9,),)","((17.4,),)","((Sg. Damansara di Kg. Melayu Subang,),)","((07/01/2023 12:30,),)"
13,3015490,3.096944,101.554167,"((0.15,),)","((7.3,),)","((7.8,),)","((8.3,),)","((Sg. Damansara di TTDI Jaya,),)","((07/01/2023 12:30,),)"
14,3015435,3.075611,101.553889,"((2.44,),)","((4.5,),)","((5.0,),)","((6.0,),)","((Sg. Damansara di Batu 3,),)","((07/01/2023 12:30,),)"
15,3015432,3.037722,101.534500,"((2.4,),)","((4.4,),)","((4.7,),)","((5.0,),)","((Sg. Klang di Taman Sri Muda,),)","((07/01/2023 12:30,),)"
16,3014401,3.048056,101.444806,"((-0.43,),)","((2.4,),)","((2.7,),)","((3.0,),)","((Sg. Klang di Bandar Klang,),)","((07/01/2023 12:30,),)"
17,3218401,3.209639,101.875861,"((131.42,),)","((133.4,),)","((133.9,),)","((134.4,),)","((Sg. Langat di TNB Pangsun,),)","((07/01/2023 12:15,),)"
18,2917401,2.994444,101.786111,"((22.57,),)","((24.4,),)","((25.4,),)","((26.4,),)","((Sg. Langat di Pekan Kajang,),)","((07/01/2023 12:15,),)"
19,3018401,3.013444,101.866056,"((48.29,),)","((48.8,),)","((49.8,),)","((50.3,),)","((Sg. Semenyih di Kg. Pasir,),)","((07/01/2023 12:30,),)"
20,2918401,2.915278,101.823611,"((20.64,),)","((24.0,),)","((24.5,),)","((25.6,),)","((Sg. Semenyih di Rinching,),)","((07/01/2023 12:30,),)"
21,2717401,2.788667,101.741972,"((6.96,),)","((8.2,),)","((8.7,),)","((9.2,),)","((Sg. Labu di Kg. Salak Tinggi,),)","((07/01/2023 12:30,),)"
22,2816441,2.992778,101.786944,"((4.96,),)","((6.4,),)","((6.9,),)","((7.5,),)","((Sg. Langat di Dengkil,),)","((07/01/2023 12:30,),)"
23,2816443,2.813472,101.641917,"((3.35,),)","((3.3,),)","((3.8,),)","((4.2,),)","((Sg. Langat di Bukit Changgang,),)","((07/01/2023 12:15,),)"
24,3217435,3.236111,101.752778,"((93.79,),)","((96.5,),)","((96.65,),)","((97.0,),)","((Empangan Klang,),)","((29/12/2022 23:30,),)"
25,3217403,3.245278,101.715278,"((57.52,),)","((60.0,),)","((61.0,),)","((62.0,),)","((Sg. Gombak di Gombak KM. 11,),)","((29/12/2022 23:30,),)"
26,3116434,3.176389,101.687500,"((29.55,),)","((32.0,),)","((32.3,),)","((33.0,),)","((Sg. Batu di Sentul,),)","((29/12/2022 23:30,),)"
27,3116433,3.173611,101.697222,"((28.17,),)","((30.0,),)","((30.5,),)","((31.0,),)","((Sg. Gombak di Jln. Tun Razak,),)","((29/12/2022 23:30,),)"
28,3117403,3.169722,101.713333,"((30.83,),)","((35.0,),)","((35.5,),)","((36.0,),)","((Sg. Bunus di Jln. Tun Razak,),)","((29/12/2022 23:15,),)"
29,3116439,3.151333,101.695306,"((25.0,),)","((29.0,),)","((30.0,),)","((31.0,),)","((Sg. Gombak di Jln. Parlimen,),)","((29/12/2022 23:30,),)"
30,3116436,3.112583,101.696583,"((23.87,),)","((28.0,),)","((29.0,),)","((30.0,),)","((Sg. Klang di Leboh Pasar,),)","((29/12/2022 23:15,),)"
31,3116430,3.138889,101.697222,"((22.64,),)","((27.0,),)","((28.25,),)","((29.5,),)","((Sg. Klang di Jambatan Sulaiman,),)","((29/12/2022 23:30,),)"
32,3016401,3.080917,101.665194,"((12.95,),)","((17.0,),)","((18.0,),)","((19.0,),)","((Sg. Klang di Jambatan Petaling,),)","((29/12/2022 23:30,),)"

In [ ]:
df['value'] = df['value'].astype(str).str.replace(r'\(|\)|,|,', '')
df['alert'] = df['alert'].astype(str).str.replace(r'\(|\)|,|,', '')
df['warning'] = df['warning'].astype(str).str.replace(r'\(|\)|,|,', '')
df['danger'] = df['danger'].astype(str).str.replace(r'\(|\)|,|,', '')
df['stationname'] = df['stationname'].astype(str).str.replace(r'\(|\)|,|,', '')
df['stationname'] = df['stationname'].astype(str).str.replace("[']", "", regex=True)
df['lastupdate'] = df['lastupdate'].astype(str).str.replace(r'\(|\)|,|,', '')
df['lastupdate'] = df['lastupdate'].astype(str).str.replace("[']", "", regex=True)

df.dtypes

C:\Users\Asus\AppData\Local\Temp\ipykernel_24656\2922546397.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['value'] = df['value'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_24656\2922546397.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['alert'] = df['alert'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_24656\2922546397.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['warning'] = df['warning'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_24656\2922546397.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['danger'] = df['danger'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_24656\2922546397.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df['stationname'] = df['stationname'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_24656\2922546397.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df['lastupdate'] = df['lastupdate'].astype(str).str.replace(r'\(|\)|,|,', '')

statid           int64
lat            float64
long           float64
value           object
alert           object
warning         object
danger          object
stationname     object
lastupdate      object
dtype: object

In [ ]:
df
df = df.astype({"value": float, "alert": float, "warning":float, "danger":float})
df

,statid,lat,long,value,alert,warning,danger,stationname,lastupdate
0,3516424,3.541417,101.662333,50.18,51.30,51.60,51.90,Sg. Selangor di Ampang Pecah,07/01/2023 12:30
1,3416403,3.469917,101.639806,32.66,35.20,35.50,35.80,Sg. Batang Kali di Batang Kali,07/01/2023 12:30
2,3808401,3.856556,100.895833,0.42,4.30,4.60,4.90,Sg. Bernam di Sg. Air Tawar,07/01/2023 12:30
3,3414421,3.402778,101.443056,6.35,6.80,7.30,7.80,Sg. Selangor di Rantau Panjang,07/01/2023 12:30
4,3313445,3.371917,101.370500,1.59,3.22,3.38,3.54,Sg. Selangor di Kg. Asahan,07/01/2023 12:30
5,3312446,3.342528,101.269111,-1.37,2.10,2.60,3.10,Sg. Selangor di Teluk Penyamun Jeti,07/01/2023 12:15
6,3214401,3.246139,101.469694,4.23,6.50,7.00,7.50,Sg. Buloh di Sri Aman,07/01/2023 12:30
7,3313470,3.306722,101.386444,2.16,3.50,4.00,4.50,Sg. Buloh di Parit Mahang,07/01/2023 12:30
8,3315401,3.304694,101.591944,33.05,34.30,34.80,35.30,Sg. Rawang di Taman Tun Teja,07/01/2023 12:30
9,3017445,3.014500,101.718667,36.39,38.50,39.00,40.00,Sg. Kuyoh di Seri Kembangan,07/01/2023 12:30
10,3015436,3.019528,101.597417,5.36,9.00,9.50,10.00,Sg. Klang di Puchong Drop,07/01/2023 12:30
11,3115403,3.112278,101.596444,14.80,17.00,17.50,18.00,Sg. Kayu Ara di Taman Mayang,07/01/2023 12:30
12,3115404,3.150056,101.540944,15.14,16.40,16.90,17.40,Sg. Damansara di Kg. Melayu Subang,07/01/2023 12:30
13,3015490,3.096944,101.554167,0.15,7.30,7.80,8.30,Sg. Damansara di TTDI Jaya,07/01/2023 12:30
14,3015435,3.075611,101.553889,2.44,4.50,5.00,6.00,Sg. Damansara di Batu 3,07/01/2023 12:30
15,3015432,3.037722,101.534500,2.40,4.40,4.70,5.00,Sg. Klang di Taman Sri Muda,07/01/2023 12:30
16,3014401,3.048056,101.444806,-0.43,2.40,2.70,3.00,Sg. Klang di Bandar Klang,07/01/2023 12:30
17,3218401,3.209639,101.875861,131.42,133.40,133.90,134.40,Sg. Langat di TNB Pangsun,07/01/2023 12:15
18,2917401,2.994444,101.786111,22.57,24.40,25.40,26.40,Sg. Langat di Pekan Kajang,07/01/2023 12:15
19,3018401,3.013444,101.866056,48.29,48.80,49.80,50.30,Sg. Semenyih di Kg. Pasir,07/01/2023 12:30
20,2918401,2.915278,101.823611,20.64,24.00,24.50,25.60,Sg. Semenyih di Rinching,07/01/2023 12:30
21,2717401,2.788667,101.741972,6.96,8.20,8.70,9.20,Sg. Labu di Kg. Salak Tinggi,07/01/2023 12:30
22,2816441,2.992778,101.786944,4.96,6.40,6.90,7.50,Sg. Langat di Dengkil,07/01/2023 12:30
23,2816443,2.813472,101.641917,3.35,3.30,3.80,4.20,Sg. Langat di Bukit Changgang,07/01/2023 12:15
24,3217435,3.236111,101.752778,93.79,96.50,96.65,97.00,Empangan Klang,29/12/2022 23:30
25,3217403,3.245278,101.715278,57.52,60.00,61.00,62.00,Sg. Gombak di Gombak KM. 11,29/12/2022 23:30
26,3116434,3.176389,101.687500,29.55,32.00,32.30,33.00,Sg. Batu di Sentul,29/12/2022 23:30
27,3116433,3.173611,101.697222,28.17,30.00,30.50,31.00,Sg. Gombak di Jln. Tun Razak,29/12/2022 23:30
28,3117403,3.169722,101.713333,30.83,35.00,35.50,36.00,Sg. Bunus di Jln. Tun Razak,29/12/2022 23:15
29,3116439,3.151333,101.695306,25.00,29.00,30.00,31.00,Sg. Gombak di Jln. Parlimen,29/12/2022 23:30
30,3116436,3.112583,101.696583,23.87,28.00,29.00,30.00,Sg. Klang di Leboh Pasar,29/12/2022 23:15
31,3116430,3.138889,101.697222,22.64,27.00,28.25,29.50,Sg. Klang di Jambatan Sulaiman,29/12/2022 23:30
32,3016401,3.080917,101.665194,12.95,17.00,18.00,19.00,Sg. Klang di Jambatan Petaling,29/12/2022 23:30

In [ ]:
df.dtypes

statid           int64
lat            float64
long           float64
value          float64
alert          float64
warning        float64
danger         float64
stationname     object
lastupdate      object
dtype: object

In [ ]:
compare = []
level = []
for i in range(0,len(df)):
    if df['value'][i] > df['danger'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/red-dot.png")
        level.append("Danger Level")
    elif df['value'][i] > df['warning'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/orange-dot.png")
        level.append("Warning Level")
    elif df['value'][i] > df['alert'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/yellow-dot.png")
        level.append("Alert Level")
    elif df['value'][i] < df['alert'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/green-dot.png")
        level.append("Normal Level")
df['Danger Level'] = compare
df['Current Status'] = level

In [ ]:
df.rename(columns = {'lat':'latitude','long':'longitude','stationname':'name','statid':'info','Danger Level':'icon'}, inplace = True)

In [ ]:
df

,info,latitude,longitude,value,alert,warning,danger,name,lastupdate,icon,Current Status
0,3516424,3.541417,101.662333,50.18,51.30,51.60,51.90,Sg. Selangor di Ampang Pecah,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
1,3416403,3.469917,101.639806,32.66,35.20,35.50,35.80,Sg. Batang Kali di Batang Kali,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
2,3808401,3.856556,100.895833,0.42,4.30,4.60,4.90,Sg. Bernam di Sg. Air Tawar,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
3,3414421,3.402778,101.443056,6.35,6.80,7.30,7.80,Sg. Selangor di Rantau Panjang,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
4,3313445,3.371917,101.370500,1.59,3.22,3.38,3.54,Sg. Selangor di Kg. Asahan,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
5,3312446,3.342528,101.269111,-1.37,2.10,2.60,3.10,Sg. Selangor di Teluk Penyamun Jeti,07/01/2023 12:15,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
6,3214401,3.246139,101.469694,4.23,6.50,7.00,7.50,Sg. Buloh di Sri Aman,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
7,3313470,3.306722,101.386444,2.16,3.50,4.00,4.50,Sg. Buloh di Parit Mahang,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
8,3315401,3.304694,101.591944,33.05,34.30,34.80,35.30,Sg. Rawang di Taman Tun Teja,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
9,3017445,3.014500,101.718667,36.39,38.50,39.00,40.00,Sg. Kuyoh di Seri Kembangan,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
10,3015436,3.019528,101.597417,5.36,9.00,9.50,10.00,Sg. Klang di Puchong Drop,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
11,3115403,3.112278,101.596444,14.80,17.00,17.50,18.00,Sg. Kayu Ara di Taman Mayang,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
12,3115404,3.150056,101.540944,15.14,16.40,16.90,17.40,Sg. Damansara di Kg. Melayu Subang,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
13,3015490,3.096944,101.554167,0.15,7.30,7.80,8.30,Sg. Damansara di TTDI Jaya,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
14,3015435,3.075611,101.553889,2.44,4.50,5.00,6.00,Sg. Damansara di Batu 3,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
15,3015432,3.037722,101.534500,2.40,4.40,4.70,5.00,Sg. Klang di Taman Sri Muda,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
16,3014401,3.048056,101.444806,-0.43,2.40,2.70,3.00,Sg. Klang di Bandar Klang,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
17,3218401,3.209639,101.875861,131.42,133.40,133.90,134.40,Sg. Langat di TNB Pangsun,07/01/2023 12:15,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
18,2917401,2.994444,101.786111,22.57,24.40,25.40,26.40,Sg. Langat di Pekan Kajang,07/01/2023 12:15,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
19,3018401,3.013444,101.866056,48.29,48.80,49.80,50.30,Sg. Semenyih di Kg. Pasir,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
20,2918401,2.915278,101.823611,20.64,24.00,24.50,25.60,Sg. Semenyih di Rinching,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
21,2717401,2.788667,101.741972,6.96,8.20,8.70,9.20,Sg. Labu di Kg. Salak Tinggi,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
22,2816441,2.992778,101.786944,4.96,6.40,6.90,7.50,Sg. Langat di Dengkil,07/01/2023 12:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
23,2816443,2.813472,101.641917,3.35,3.30,3.80,4.20,Sg. Langat di Bukit Changgang,07/01/2023 12:15,http://maps.google.com/mapfiles/ms/icons/yello...,Alert Level
24,3217435,3.236111,101.752778,93.79,96.50,96.65,97.00,Empangan Klang,29/12/2022 23:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
25,3217403,3.245278,101.715278,57.52,60.00,61.00,62.00,Sg. Gombak di Gombak KM. 11,29/12/2022 23:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
26,3116434,3.176389,101.687500,29.55,32.00,32.30,33.00,Sg. Batu di Sentul,29/12/2022 23:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
27,3116433,3.173611,101.697222,28.17,30.00,30.50,31.00,Sg. Gombak di Jln. Tun Razak,29/12/2022 23:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
28,3117403,3.169722,101.713333,30.83,35.00,35.50,36.00,Sg. Bunus di Jln. Tun Razak,29/12/2022 23:15,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
29,3116439,3.151333,101.695306,25.00,29.00,30.00,31.00,Sg. Gombak di Jln. Parlimen,29/12/2022 23:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
30,3116436,3.112583,101.696583,23.87,28.00,29.00,30.00,Sg. Klang di Leboh Pasar,29/12/2022 23:15,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
31,3116430,3.138889,101.697222,22.64,27.00,28.25,29.50,Sg. Klang di Jambatan Sulaiman,29/12/2022 23:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level
32,3016401,3.080917,101.665194,12.95,17.00,18.00,19.00,Sg. Klang di Jambatan Petaling,29/12/2022 23:30,http://maps.google.com/mapfiles/ms/icons/green...,Normal Level

In [ ]:
df.dtypes
df2 = df[['latitude','longitude','name','info','icon','value']]

In [ ]:
df2.dtypes

latitude     float64
longitude    float64
name          object
info           int64
icon          object
value        float64
dtype: object

In [ ]:
from sqlalchemy import create_engine


#con = MySQLdb.connect(user='root', password='',host='localhost', database='website_myflood')
#engine = create_engine("mysql+pymysql://root:@localhost/website_myflood")
#df2.to_sql('locations', con = engine, if_exists='replace',index=False)
con = MySQLdb.connect(user='root', password='',host='localhost', database='myfloodlaravel')
engine = create_engine("mysql+pymysql://root:@localhost/myfloodlaravel")
df.to_sql('locations', con = engine, if_exists='replace', index=False)

33