In [1]:
import pandas as pd
import folium
from pandas.io import sql 
import MySQLdb

con = MySQLdb.connect(user='root', password='',host='localhost', database='website_myflood')
concursor = con.cursor()

df = pd.read_csv("latlong.csv", names=['statid','lat','long']) 
df.dropna(inplace=True)
df

    statid       lat        long
0  3217435  3.236111  101.752778
1  3217403  3.245278  101.715278
2  3116434  3.176389  101.687500
3  3116433  3.173611  101.697222
4  3117403  3.169722  101.713333
5  3116439  3.151333  101.695306
6  3116435  3.150500  101.698472
7  3116436  3.112583  101.696583
8  3116430  3.138889  101.697222
9  3016401  3.080917  101.665194

In [2]:
df['value'] = ''
df['alert'] = ''
df['warning'] = ''
df['danger'] = ''

In [3]:
con = MySQLdb.connect(user='root', password='',host='localhost', database='website_myflood')
concursor = con.cursor()

for i in range(0,len(df)):
   x = df['statid'][i]
   state = ("SELECT CurrentWaterLevel FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['value'][i] = result
for i in range(0,len(df)):
   x = df['statid'][i]
   state = ("SELECT Alert FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['alert'][i] = result
for i in range(0,len(df)):
   x = df['statid'][i]
   state = ("SELECT Warning FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['warning'][i] = result
for i in range(0,len(df)):
   x = df['statid'][i]
   state = ("SELECT Danger FROM `selangorscrape` WHERE `Station ID` = %(x)s")
   concursor.execute(state, {'x': x })
   result = concursor.fetchall()
   print(result)
   df['danger'][i] = result

((93.29,),)
((57.52,),)
((29.53,),)
((28.17,),)
((30.85,),)
((25.0,),)
((25.29,),)
((23.84,),)
((22.65,),)
((12.94,),)
((96.5,),)
((60.0,),)
((32.0,),)
((30.0,),)
((35.0,),)
((29.0,),)
((28.0,),)
((28.0,),)
((27.0,),)
((17.0,),)
((96.65,),)
((61.0,),)
((32.3,),)
((30.5,),)
((35.5,),)
((30.0,),)
((29.0,),)
((29.0,),)
((28.25,),)
((18.0,),)
((97.0,),)
((62.0,),)
((33.0,),)
((31.0,),)
((36.0,),)
((31.0,),)
((30.0,),)
((30.0,),)
((29.5,),)
((19.0,),)

C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\3582417952.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['value'][i] = result
C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\3582417952.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['alert'][i] = result
C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\3582417952.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['warning'][i] = result
C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\3582417952.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['danger'][i] = result

In [4]:
df['value'] = df['value'].astype(str).str.replace(r'\(|\)|,|,', '')
df['alert'] = df['alert'].astype(str).str.replace(r'\(|\)|,|,', '')
df['warning'] = df['warning'].astype(str).str.replace(r'\(|\)|,|,', '')
df['danger'] = df['danger'].astype(str).str.replace(r'\(|\)|,|,', '')

C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\189248526.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['value'] = df['value'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\189248526.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['alert'] = df['alert'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\189248526.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['warning'] = df['warning'].astype(str).str.replace(r'\(|\)|,|,', '')
C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\189248526.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df['danger'] = df['danger'].astype(str).str.replace(r'\(|\)|,|,', '')

In [5]:
df

    statid       lat        long  value alert warning danger
0  3217435  3.236111  101.752778  93.29  96.5   96.65   97.0
1  3217403  3.245278  101.715278  57.52  60.0    61.0   62.0
2  3116434  3.176389  101.687500  29.53  32.0    32.3   33.0
3  3116433  3.173611  101.697222  28.17  30.0    30.5   31.0
4  3117403  3.169722  101.713333  30.85  35.0    35.5   36.0
5  3116439  3.151333  101.695306   25.0  29.0    30.0   31.0
6  3116435  3.150500  101.698472  25.29  28.0    29.0   30.0
7  3116436  3.112583  101.696583  23.84  28.0    29.0   30.0
8  3116430  3.138889  101.697222  22.65  27.0   28.25   29.5
9  3016401  3.080917  101.665194  12.94  17.0    18.0   19.0

In [6]:
df
df = df.astype({"value": float, "alert": float, "warning":float, "danger":float})

In [7]:
df['value'][0] = 97.0

C:\Users\Asus\AppData\Local\Temp\ipykernel_54952\2180280639.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['value'][0] = 97.0

In [8]:
compare = []
for i in range(0,len(df)):
    if df['value'][i] > df['danger'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/red-dot.png")
    elif df['value'][i] > df['warning'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/yellow-dot.png")
    elif df['value'][i] > df['alert'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/blue-dot.png")
    elif df['value'][i] < df['alert'][i]:
        compare.append("http://maps.google.com/mapfiles/ms/icons/green-dot.png")
df['Danger Level'] = compare

In [9]:
df

,statid,lat,long,value,alert,warning,danger,Danger Level
0,3217435,3.236111,101.752778,97.00,96.5,96.65,97.0,http://maps.google.com/mapfiles/ms/icons/yello...
1,3217403,3.245278,101.715278,57.52,60.0,61.00,62.0,http://maps.google.com/mapfiles/ms/icons/green...
2,3116434,3.176389,101.687500,29.53,32.0,32.30,33.0,http://maps.google.com/mapfiles/ms/icons/green...
3,3116433,3.173611,101.697222,28.17,30.0,30.50,31.0,http://maps.google.com/mapfiles/ms/icons/green...
4,3117403,3.169722,101.713333,30.85,35.0,35.50,36.0,http://maps.google.com/mapfiles/ms/icons/green...
5,3116439,3.151333,101.695306,25.00,29.0,30.00,31.0,http://maps.google.com/mapfiles/ms/icons/green...
6,3116435,3.150500,101.698472,25.29,28.0,29.00,30.0,http://maps.google.com/mapfiles/ms/icons/green...
7,3116436,3.112583,101.696583,23.84,28.0,29.00,30.0,http://maps.google.com/mapfiles/ms/icons/green...
8,3116430,3.138889,101.697222,22.65,27.0,28.25,29.5,http://maps.google.com/mapfiles/ms/icons/green...
9,3016401,3.080917,101.665194,12.94,17.0,18.00,19.0,http://maps.google.com/mapfiles/ms/icons/green...

In [10]:
df.rename(columns = {'lat':'latitude','long':'longitude','value':'name','statid':'info','Danger Level':'icon'}, inplace = True)

In [11]:
df

,info,latitude,longitude,name,alert,warning,danger,icon
0,3217435,3.236111,101.752778,97.00,96.5,96.65,97.0,http://maps.google.com/mapfiles/ms/icons/yello...
1,3217403,3.245278,101.715278,57.52,60.0,61.00,62.0,http://maps.google.com/mapfiles/ms/icons/green...
2,3116434,3.176389,101.687500,29.53,32.0,32.30,33.0,http://maps.google.com/mapfiles/ms/icons/green...
3,3116433,3.173611,101.697222,28.17,30.0,30.50,31.0,http://maps.google.com/mapfiles/ms/icons/green...
4,3117403,3.169722,101.713333,30.85,35.0,35.50,36.0,http://maps.google.com/mapfiles/ms/icons/green...
5,3116439,3.151333,101.695306,25.00,29.0,30.00,31.0,http://maps.google.com/mapfiles/ms/icons/green...
6,3116435,3.150500,101.698472,25.29,28.0,29.00,30.0,http://maps.google.com/mapfiles/ms/icons/green...
7,3116436,3.112583,101.696583,23.84,28.0,29.00,30.0,http://maps.google.com/mapfiles/ms/icons/green...
8,3116430,3.138889,101.697222,22.65,27.0,28.25,29.5,http://maps.google.com/mapfiles/ms/icons/green...
9,3016401,3.080917,101.665194,12.94,17.0,18.00,19.0,http://maps.google.com/mapfiles/ms/icons/green...

In [12]:
df2 = df[['latitude','longitude','name','info','icon']]

In [13]:
df2

,latitude,longitude,name,info,icon
0,3.236111,101.752778,97.00,3217435,http://maps.google.com/mapfiles/ms/icons/yello...
1,3.245278,101.715278,57.52,3217403,http://maps.google.com/mapfiles/ms/icons/green...
2,3.176389,101.687500,29.53,3116434,http://maps.google.com/mapfiles/ms/icons/green...
3,3.173611,101.697222,28.17,3116433,http://maps.google.com/mapfiles/ms/icons/green...
4,3.169722,101.713333,30.85,3117403,http://maps.google.com/mapfiles/ms/icons/green...
5,3.151333,101.695306,25.00,3116439,http://maps.google.com/mapfiles/ms/icons/green...
6,3.150500,101.698472,25.29,3116435,http://maps.google.com/mapfiles/ms/icons/green...
7,3.112583,101.696583,23.84,3116436,http://maps.google.com/mapfiles/ms/icons/green...
8,3.138889,101.697222,22.65,3116430,http://maps.google.com/mapfiles/ms/icons/green...
9,3.080917,101.665194,12.94,3016401,http://maps.google.com/mapfiles/ms/icons/green...

In [14]:
from sqlalchemy import create_engine


con = MySQLdb.connect(user='root', password='',host='localhost', database='website_myflood')
engine = create_engine("mysql+pymysql://root:@localhost/website_myflood")
df2.to_sql('locations', con = engine, if_exists='append',index=False)

10